version: '2'

services:

  springApp:
    container_name:
      springApp-instance
    restart: unless-stopped
    image: "dimamon/springboot-influxdb-sender:1.0-SNAPSHOT"
    ports:
    - 8081:8081
    # connect to influx config
    environment:
    - DB_URL=influxdb-instance
    - DB_NAME=for_grafana
    - DB_PORT=8086
    - DB_USERNAME=root
    - DB_PASSWORD=root
    depends_on:
    - "influxdb"

  influxdb:
    container_name:
      influxdb-instance
    restart: unless-stopped
    image: "influxdb"
    ports:
    - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb

volumes:
  influxdb:
    external:
      name: influxdb