apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-app
spec:
  selector:
    matchLabels:
      app: metrics-app
  replicas: 1
  template:
    metadata:
      labels:
        app: metrics-app
    spec:
      containers:
      - name: metrics-app
        image: dimamon/springboot-influxdb-sender:2.2-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 200m
            memory: 350Mi
        env:
        - name: JAVA_OPTS
          value: "-Xms300m -Xmx300m"
        - name: METRICS_ENABLED
          value: "true"
        - name: DB_URL
          value: "46.119.5.94"
        - name: DB_NAME
          value: "for_grafana"
        - name: DB_PORT
          value: "8086"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: "root"
        - name: BASIC_CPU_LOAD
          value: "1000000"
        - name: BASIC_RAM_LOAD
          value: "10000"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name