db:
  url: ${DB_URL}
  name: ${DB_NAME}
  port: ${DB_PORT}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  store_metrics: 3d
  metricsEnabled: ${METRICS_ENABLED}

kubernetes:
  node_name: ${NODE_NAME}
  node_cpu: ${NODE_CPU_LIMIT}
  pod_name: ${POD_NAME}
  pod_cpu: ${POD_CPU_LIMIT}

workload:
  basic_cpu: ${BASIC_CPU_LOAD}
  basic_ram: ${BASIC_RAM_LOAD}