apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elastic-dev
spec:
  type: NodePort
  selector:
    app: elastic-dev
  ports:
    - name: elastic-rest-api
      port: 9200
      targetPort: elk-rest-port
      protocol: TCP
    - name: elastic-nodes-communication
      port: 9300
      targetPort: elk-comm-port
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elastic-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elastic-dev
    spec:
      initContainers:
        - name: fix-the-volume-permission
          image: busybox
          command:
            - sh
            - -c
            - chown -R 1000:1000 /usr/share/elasticsearch/data
          securityContext:
            privileged: true
          volumeMounts:
            - name: elastic-persistent-storage-ssd
              mountPath: /usr/share/elasticsearch/data
        - name: increase-the-vm-max-map-count
          image: busybox
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
        - name: increase-the-ulimit
          image: busybox
          command:
            - sh
            - -c
            - ulimit -n 65536
          securityContext:
            privileged: true
      containers:
        - name: elastic-dev
          image: elasticsearch:6.5.1
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ES_JAVA_OPTS
              value: -Xms1000m -Xmx1000m # JVM Heap size
            - name: PROCESSORS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          ports:
            - containerPort: 9200
              name: elk-rest-port # Rest api
            - containerPort: 9300
              name: elk-comm-port # Communication between nodes
          resources:
            requests:
              cpu: 0.5
              memory: 1Gi
            limits:
              cpu: 0.6
              memory: 1.5Gi
          volumeMounts:
            - name: elastic-persistent-storage-ssd
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elastic-persistent-storage-ssd
          emptyDir: {}