apiVersion: v1
kind: Service
metadata:
  name: kibana-service-dev
  labels:
    app: kibana-dev
spec:
  type: NodePort
  selector:
    app: kibana-dev
  ports:
    - name: kibana-http
      port: 5601
      targetPort: http
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana-dev
    spec:
      containers:
        - name: kibana
          image: kibana:6.5.4
          env:
            - name: KIBANA_ES_URL
              value: "http://elasticsearch.default.svc.cluster.local:9200"
            - name: KUBERNETES_TRUST_CERT
              value: "true"
          ports:
            - containerPort: 5601
              name: http
              protocol: TCP